{{/*
Helm template for "serviceAccount" resource
serviceAccount is required for IRSA (IAM Role for Service Account).
*/}}

{{- range .Values.runnerDeployments }}
{{- if .serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .runnerName }}
  labels:
    {{- include "actions-runner.labels" $ | nindent 4 }}
  {{- with .serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .serviceAccount.automountServiceAccountToken | default true }}
{{- with .serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}