apiVersion: v2
name: istio-envoyfilters
description: A Helm chart for managing Istio EnvoyFilter resources. This chart enables customization of Envoy proxy configurations across namespaces.
deprecated: false
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - istio
  - envoyfilter
  - envoy
  - service-mesh
  - custom-resources
maintainers:
  - name: younsl
    email: cysl@kakao.com
    url: https://github.com/younsl
home: https://istio.io/latest/docs/reference/config/networking/envoy-filter/
sources:
  - https://github.com/istio/istio
  - https://github.com/younsl/charts
annotations:
  "helm.sh/skip-test": "true"
  "helm.sh/skip-test-reason": "Only CRD resources, requires Istio to be installed"
