{{- if semverCompare ">=1.34.0-0" .Capabilities.KubeVersion.Version }}
{{- range $policyKey, $policyValue := .Values.mutatingAdmissionPolicies }}
{{- if $policyValue.enabled }}
{{- $policyName := $policyValue.name }}
{{- range $bindingKey, $bindingValue := $policyValue.bindings }}
{{- if $bindingValue.enabled }}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: {{ $bindingValue.name }}
  labels:
    {{- include "admission-policies.labels" $ | nindent 4 }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  policyName: {{ $policyName }}
  {{- with $bindingValue.matchResources }}
  matchResources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $bindingValue.paramRef }}
  paramRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
